# 多表关联、二次分表、绑定表场景
spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: db0
      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://82.156.205.178:3306/db0?serverTimezone=GMT%2B8&characterEncoding=UTF-8
        username: root
        password: madao123
    sharding:
      tables:
        # 表名
        user:
          # 真实表,数据库、表的分库分表情况说明
          actual-data-nodes: db0.user_${0..1},db0.user_1_woman,db0.user_1_man
          table-strategy:
            complex:
              shardingColumns: age,gender
              algorithmClassName: com.madaoo.example.config.PreciseModuloTableShardingAlgorithm
        test:
          # 真实表,数据库、表的分库分表情况说明
          actual-data-nodes: db0.test_${0..1}
          table-strategy:
            complex:
              shardingColumns: age,gender
              algorithmClassName: com.madaoo.example.config.PreciseModuloTableShardingAlgorithm
      # 两个同样分片逻辑的表绑定后sql会比没有绑定的情况少
      binding-tables: test,user
    props:
      sql:
        show: true
